sudo: required  # Required for docker
services:
  - docker

install:
  - npm install -g dockerlint

script:
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo80 --docker-image steingabelgaard/odoo-80-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo-shippable --docker-image steingabelgaard/odoo-80-image-shippable-auto:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo90 --docker-image steingabelgaard/odoo-90-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo100 --docker-image steingabelgaard/odoo-100-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo110 --docker-image steingabelgaard/odoo-110-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo120 --docker-image steingabelgaard/odoo-120-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo130 --docker-image steingabelgaard/odoo-130-image:latest
  - docker run -it --rm --name fix-vim-snippet -v ${TRAVIS_BUILD_DIR}/odoo-shippable/scripts/fix-vim-snippet.py:/root/fix-vim-snippet.py steingabelgaard/odoo-80-image-shippable-auto python /root/fix-vim-snippet.py --extensions sh,sql,python

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push steingabelgaard/odoo-80-image-shippable-auto
  
